In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
suma

array([5, 7, 9])

In [4]:
np.random.uniform(10, 20, 10).astype(int)

array([14, 19, 13, 14, 16, 14, 12, 17, 19, 17])

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('iris', header = None)

PermissionError: [Errno 13] Permission denied: './'

In [ ]:
df

In [ ]:
df.head()

In [ ]:
df.tail(10)

In [ ]:
nombres = ['longitud sepalo', 'ancho sepalo', 'longitud petalo', 'ancho petalo', 'clase']
nombres

In [ ]:
df.columns = nombres

In [ ]:
df.head()

In [ ]:
df.index

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
df['clase'].value_counts()

In [ ]:
df.T

In [ ]:
df.sort_values('ancho sepalo', ascending = True)

In [ ]:
df['longitud petalo'][:3]

In [ ]:
df[ ['longitud sepalo', 'longitud petalo'] ]

In [ ]:
df [df['longitud sepalo']>5]

In [ ]:
df [(df['longitud sepalo']>5) & (df['longitud petalo']>3)]

In [ ]:
df['longitud sepalo'].max()

In [ ]:
df['longitud sepalo'].idxmax()

In [ ]:
df.loc[131]

In [ ]:
df.isna()

In [ ]:
df.isna().sum()

In [ ]:
import numpy as np

In [ ]:
df['longitud petalo'][:2] = np.nan

In [ ]:
df.head()

In [ ]:
df.isna().sum()

In [ ]:
df['longitud petalo'].fillna(2)

In [ ]:
df['longitud petalo'] = df['longitud petalo'].fillna(2)
df.head()

In [ ]:
df['ancho sepalo'].apply(lambda x: -x)

In [ ]:
df['ancho sepalo'].apply(lambda x: x**2)

In [ ]:
df.groupby('clase')['ancho petalo'].mean()

In [ ]:
df.head()

In [ ]:
condiciones = [
    (df['longitud sepalo'] <= 2),
    (df['longitud sepalo'] > 3) & (df['longitud sepalo'] <= 5),
    (df['longitud sepalo'] > 5)
]

etiquetas = ['N1', 'N2', 'N3']

df['nivel sepalos'] = np.select(condiciones, etiquetas, default='No clasificado')

df

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df['longitud petalo'].plot()

In [ ]:
df.plot()

In [ ]:
df.plot(figsize=[12,10])

In [ ]:
df['longitud petalo'].plot(kind= 'bar')

In [ ]:
df = pd.read_csv('data/personas.csv')
df.head()

In [ ]:
df.columns

In [ ]:
nombres = ['altura', 'peso', 'ingreso hora', 'horas trabajadas semana', 'ausencias']

In [ ]:
df.columns = nombres

In [ ]:
df.head()

### Actividad en clase

- Crear una columna edad (rango de 18 a 50 años).
- Agregar nivel educativo segun edad. Si está entre 18 y 24 es profesional, si está entre 25 y 30 es magíster, mayor a 31 doctor. Para esto deberá crear la columna Nivel Educativo, tipo str.
- Calcular y crear la columna Pago sin Ausencias y Pago con Ausencias. Deben ser tipo entero (int).
- Calcular la edad promedio de ausencias.
- Crear una columna que permita clasificar el ingreso de la persona. Si el dinero total al mes es inferior a un mínimo, colocar la etiqueta N1, si está entre un mínimo y 2, colocar la etiqueta N2 y sueperior a dos salarios mínimos, la etiqueta N3.
- Realizar 3 gráficos que considere pertinentes para la interpretación de datos.

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('Datos/EjercicioAvocado.ipynb')
df

altura        peso       ingreso  horas_trabajadas  ausencias
0    134.433878   70.617864   9973.577534         40.905476          4
1    167.158746  109.268295   8961.047249         41.576483          4
2    141.480812   81.034644   7437.977263         41.369239          5
3    123.227119   57.884172  12064.915290         41.537211          3
4    143.554951   93.581093   9296.396167         40.441203          4
..          ...         ...           ...               ...        ...
995  169.059462  109.612155   9998.522402         41.110352          4
996  151.873081   91.697127   6867.097603         40.617061          5
997  131.156800   78.301155   9757.539280         40.798085          4
998  156.454396   94.163603  11044.031510         41.443604          3
999  149.558353   87.134622  13222.253800         41.402637          2

[1000 rows x 5 columns]

In [2]:
df['Edad'] = np.random.uniform(18, 50, 1000).astype(int)
df

altura        peso       ingreso  horas_trabajadas  ausencias  Edad
0    134.433878   70.617864   9973.577534         40.905476          4    48
1    167.158746  109.268295   8961.047249         41.576483          4    49
2    141.480812   81.034644   7437.977263         41.369239          5    32
3    123.227119   57.884172  12064.915290         41.537211          3    20
4    143.554951   93.581093   9296.396167         40.441203          4    41
..          ...         ...           ...               ...        ...   ...
995  169.059462  109.612155   9998.522402         41.110352          4    48
996  151.873081   91.697127   6867.097603         40.617061          5    43
997  131.156800   78.301155   9757.539280         40.798085          4    40
998  156.454396   94.163603  11044.031510         41.443604          3    27
999  149.558353   87.134622  13222.253800         41.402637          2    18

[1000 rows x 6 columns]

In [3]:
condiciones = [
    (df['Edad'] >= 18) & (df['Edad'] <= 24),
    (df['Edad'] >= 25) & (df['Edad'] <= 30),
    (df['Edad'] >= 31)
]

etiquetas = ['Profesional', 'Magister', 'Doctor']

df['Nivel Educativo'] = np.select(condiciones, etiquetas, default='No clasificado')

df

altura        peso       ingreso  horas_trabajadas  ausencias  Edad  \
0    134.433878   70.617864   9973.577534         40.905476          4    48   
1    167.158746  109.268295   8961.047249         41.576483          4    49   
2    141.480812   81.034644   7437.977263         41.369239          5    32   
3    123.227119   57.884172  12064.915290         41.537211          3    20   
4    143.554951   93.581093   9296.396167         40.441203          4    41   
..          ...         ...           ...               ...        ...   ...   
995  169.059462  109.612155   9998.522402         41.110352          4    48   
996  151.873081   91.697127   6867.097603         40.617061          5    43   
997  131.156800   78.301155   9757.539280         40.798085          4    40   
998  156.454396   94.163603  11044.031510         41.443604          3    27   
999  149.558353   87.134622  13222.253800         41.402637          2    18   

    Nivel Educativo  
0            Doctor  
1            Doctor  
2            Doctor  
3       Profesional  
4            Doctor  
..              ...  
995          Doctor  
996          Doctor  
997          Doctor  
998        Magister  
999     Profesional  

[1000 rows x 7 columns]

In [7]:
df['horas_trabajadas'] = df['horas_trabajadas'].round(2)
df['ingreso'] = df['ingreso'].round(2)

df['Total Horas Mensual'] = (df['horas_trabajadas'] - df['ausencias']) * 4

df['Pago Total Mes'] = df['Total Horas Mensual'] * df['ingreso']
df['Pago Total Mes'] = df['Pago Total'].round(2)
df

KeyError: 'Pago Total'

In [60]:
df.groupby('Edad')['ausencias'].mean()

Edad
18    3.360000
19    3.625000
20    3.512195
21    3.629630
22    3.615385
23    3.555556
24    3.333333
25    3.542857
26    3.789474
27    3.464286
28    3.447368
29    3.866667
30    3.740741
31    3.432432
32    3.909091
33    3.777778
34    3.826087
35    3.647059
36    3.475000
37    3.580645
38    3.636364
39    3.444444
40    3.821429
41    3.578947
42    3.840000
43    3.411765
44    3.225000
45    3.368421
46    3.576923
47    3.814815
48    3.875000
49    3.437500
Name: ausencias, dtype: float64